services:
  ipfs:
    image: ipfs-api
    healthcheck:
      test: ipfs id
      interval: 1s
      timeout: 3s
      retries: 30
  redis:
    image: crossedbot/redisedge
    healthcheck:
      test: redis-cli -u redis://127.0.0.1:6379 ping
      interval: 1s
      timeout: 3s
      retries: 30
  insights:
    image: redislabs/redisinsight
    depends_on:
      redis:
        condition: service_healthy
    links:
      - redis
    ports:
      - "${INSIGHTS_PORT}:8001"
    volumes:
      - redisinsight:/db
  indexer:
    image: crossedbot/hermes-indexer
    command: "-k '${KEY}' -s '${SALT}'"
    depends_on:
      ipfs:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - ipfs
      - redis
    ports:
      - "${INDEXER_PORT}:8888"
  replayer:
    image: crossedbot/hermes-replayer
    command: "-k '${KEY}' -s '${SALT}'"
    depends_on:
      ipfs:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - ipfs
      - redis
    ports:
      - "${REPLAYER_PORT}:8989"
volumes:
  redisinsight: {}
