// Code generated by MockGen. DO NOT EDIT.
// Source: indexer/controller/controller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/crossedbot/hermes-archiver/pkg/indexer/models"
	simplecdxj "github.com/crossedbot/simplecdxj"
	gomock "github.com/golang/mock/gomock"
)

// MockIndexerController is a mock of Controller interface.
type MockIndexerController struct {
	ctrl     *gomock.Controller
	recorder *MockIndexerControllerMockRecorder
}

// MockIndexerControllerMockRecorder is the mock recorder for MockIndexerController.
type MockIndexerControllerMockRecorder struct {
	mock *MockIndexerController
}

// NewMockIndexerController creates a new mock instance.
func NewMockIndexerController(ctrl *gomock.Controller) *MockIndexerController {
	mock := &MockIndexerController{ctrl: ctrl}
	mock.recorder = &MockIndexerControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexerController) EXPECT() *MockIndexerControllerMockRecorder {
	return m.recorder
}

// FindRecords mocks base method.
func (m *MockIndexerController) FindRecords(surt string, types []simplecdxj.RecordType, before, after string, limit int) (models.Records, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRecords", surt, types, before, after, limit)
	ret0, _ := ret[0].(models.Records)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRecords indicates an expected call of FindRecords.
func (mr *MockIndexerControllerMockRecorder) FindRecords(surt, types, before, after, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRecords", reflect.TypeOf((*MockIndexerController)(nil).FindRecords), surt, types, before, after, limit)
}

// GetRecord mocks base method.
func (m *MockIndexerController) GetRecord(id string) (models.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecord", id)
	ret0, _ := ret[0].(models.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecord indicates an expected call of GetRecord.
func (mr *MockIndexerControllerMockRecorder) GetRecord(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecord", reflect.TypeOf((*MockIndexerController)(nil).GetRecord), id)
}
